from typing import Protocol, Sequence


class Runner(Protocol):
    """Prepared inputs keep tokenization outside inference timing."""

    def load(self) -> None: ...
    def preprocess(self, texts: Sequence[str]) -> object: ...
    def predict(self, inputs: object) -> Sequence[Sequence[float]]: ...
    def metadata(self) -> dict: ...
